### PR TITLE
Make sendfd work on non-linux systems

### PR DESCRIPTION
**Pull request by jedisct1**
The crate currently only works on Linux. It breaks on BSD and MacOS because of assertions about the message length type.

This simple changeset makes it compatible with other platforms.

### CODE REVIEW

**Comment by jedisct1** [comment]
Fixes #5

**Comment by nagisa** [comment]
Ah, sorry for missing this!

It appears that I wasn’t watching the repo for whatever reason and didn’t receive a notification.

This LGTM, I will merge in a second once I figure out which repo  is actually the canonical, this one or the one at https://github.com/standard-ai/sendfd.

**Comment by nagisa** [comment]
I did merge this into `standard-ai/sendfd`, thanks! I will be looking into how to properly remove this crate and unfork the `standard-ai` one.

**Comment by jedisct1** [comment]
Thank you!

**Pull request closed without merging**
